{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:05:17,658+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:05:17,661+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:11:59,991+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:11:59,993+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:15:54,159+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:15:54,161+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:15:54,303+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:15:54,305+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:15:54,500+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:15:54,514+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:15:54,695+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:15:54,697+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:15:54,838+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:15:54,840+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:15:54,973+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:15:54,975+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:15:55,129+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:15:55,130+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:15:55,268+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:15:55,270+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:15:55,416+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:15:55,418+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:15:55,577+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:15:55,580+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:15:55,745+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:15:55,748+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:15:55,893+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:15:55,894+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[__symbol_conversion:1352] data_ws","message":{"code":-300,"message":"Please provide a valid symbol","s":"error","type":"sub","invalid_symbols":["NSE:M%26M-EQ"]},"timestamp":"2025-09-07 22:15:56,036+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:15:56,183+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:15:56,186+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:15:56,339+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:15:56,341+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:15:56,477+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:15:56,479+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:15:56,663+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:15:56,665+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:15:56,858+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:15:56,861+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:15:56,996+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:15:56,998+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:15:57,197+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:15:57,200+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:15:57,348+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:15:57,349+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:15:57,489+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:15:57,491+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:15:57,624+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:15:57,626+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:15:57,771+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:15:57,773+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:15:57,910+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:15:57,913+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:15:58,054+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:15:58,056+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:15:58,206+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:15:58,208+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:15:58,351+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:15:58,353+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:15:58,492+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:15:58,494+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:15:58,628+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:15:58,630+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:15:58,758+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:15:58,760+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:15:58,901+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:15:58,902+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:15:59,037+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:15:59,039+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:15:59,184+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:15:59,187+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:15:59,335+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:15:59,338+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:15:59,487+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:15:59,490+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:15:59,642+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:15:59,644+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:16:46,715+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:16:46,717+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:16:46,852+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:16:46,853+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:16:47,155+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:16:47,156+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:16:47,310+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:16:47,313+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:16:47,455+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:16:47,457+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:16:47,613+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:16:47,616+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:16:47,782+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:16:47,785+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:16:47,933+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:16:47,936+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:16:48,075+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:16:48,078+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:16:48,223+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:16:48,225+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:16:48,367+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:16:48,369+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:16:48,508+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:16:48,511+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:16:48,661+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:16:48,664+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:16:48,815+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:16:48,818+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:16:48,971+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:16:48,973+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:16:49,126+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:16:49,129+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:16:49,270+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:16:49,271+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:16:49,412+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:16:49,413+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:16:49,549+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:16:49,551+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:16:49,688+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:16:49,690+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:16:49,837+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:16:49,840+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:16:49,977+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:16:49,979+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:16:50,129+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:16:50,131+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:16:50,275+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:16:50,277+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:16:50,414+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:16:50,415+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:16:50,563+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:16:50,565+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:16:50,717+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:16:50,719+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:16:50,861+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:16:50,865+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:16:51,003+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:16:51,005+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:16:51,140+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:16:51,143+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:16:51,281+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:16:51,284+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:16:51,426+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:16:51,428+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:16:51,567+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:16:51,569+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:16:51,710+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:16:51,713+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:16:51,847+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:16:51,850+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"cannot access local variable 'hsm_symbol' where it is not associated with a value","timestamp":"2025-09-07 22:16:51,993+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 115, in symbol_to_hsmtoken\n    datadict[hsm_symbol] = symbol\n             ^^^^^^^^^^\nUnboundLocalError: cannot access local variable 'hsm_symbol' where it is not associated with a value","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-09-07 22:16:51,996+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"/home/karthik/.pyenv/versions/3.11.9/lib/python3.11/site-packages/fyers_apiv3/FyersWebsocket/data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"Connection to remote host was lost.","timestamp":"2025-09-08 01:04:09,479+0530","service":"FyersDataSocket"}
